### ISSUE TITLE
Domain Driven Design Made Functional

### ISSUE THREAD

**Issue by imihalcea** [dotnettlse/call-for-paper#1]
### Le(s) speaker(s)
Ionut Mihalcea

### Description de votre session

Nous vous proposons un retour sur le livre "Domain Modeling Made Functional" de Scott Walchin. Après une introduction du Domain Driven Design nous continuerons avec des détails d’implémentation afin de pouvoir se rendre compte de l'apport de la programmation fonctionnelle sur un cas réel d'application.

### Informations diverses

* Niveau de difficulté :  débutant, confirmé
* Durée : 1h30
* Format : slides, live-coding
* Disponibilités : 03/2020 et après

### Règles de courtoisie

- [x] J'ai lu le [code de conduite](https://fr.confcodeofconduct.com/), j'en comprends la teneur et je m'engage à le respecter

**Comment by glacasa** [comment]
https://www.meetup.com/fr-FR/Meetup-NET-Toulouse/events/267899848/
